spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://alchemist.coyyrtneae5j.ap-northeast-2.rds.amazonaws.com:3306/Alchemist?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASS}
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mail:
    title: ${MAIL_TITLE}
    exp: ${MAIL_EXP}
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_ADDRESS}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

code:
  min: ${MIN_VALUE}
  max: ${MAX_VALUE}