spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alchemist?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASS}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernates:
        show_sql: true
        format_sql: true
jwt:
  secret: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
